# Generated by Django 2.2 on 2020-02-09 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gimnasios', '0002_auto_20200209_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rutina', models.CharField(max_length=100)),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasios.Gimnasios')),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('repeticiones', models.IntegerField()),
                ('dia', models.CharField(max_length=15)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.Rutinas')),
            ],
        ),
    ]
