# Generated by Django 2.2 on 2020-02-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gimnasios',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
