# Generated by Django 2.2 on 2020-02-20 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasios', '0002_auto_20200209_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasios.Gimnasios')),
            ],
        ),
    ]
