# Generated by Django 2.2 on 2020-03-04 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gimnasios', '0004_auto_20200220_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasios.Gimnasios')),
            ],
        ),
    ]
