# Generated by Django 2.2 on 2020-02-09 19:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasios', '0001_initial'),
        ('usuarios', '0003_auto_20200209_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocliente',
            name='gym_socio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gimnasios.Gimnasios'),
            preserve_default=False,
        ),
    ]
