# Generated by Django 2.2 on 2020-02-20 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasios', '0003_planes'),
        ('usuarios', '0006_auto_20200209_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocliente',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gimnasios.Planes'),
            preserve_default=False,
        ),
    ]
