# Generated by Django 2.2 on 2020-03-04 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0001_initial'),
        ('usuarios', '0008_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='retosUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Retos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
