# Generated by Django 2.2 on 2020-03-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_asistencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencias',
            name='fecha',
            field=models.DateField(auto_now=True, unique=True),
        ),
    ]
