# Generated by Django 2.2 on 2020-03-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20200310_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencias',
            name='asistio',
            field=models.BooleanField(default=True),
        ),
    ]
