# Generated by Django 2.2 on 2020-03-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_asistencias_asistio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='is_admin_gym',
        ),
        migrations.AddField(
            model_name='infocliente',
            name='altura',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='infocliente',
            name='cintura',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infocliente',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infocliente',
            name='pecho',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infocliente',
            name='peso',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='infocliente',
            name='piernas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infocliente',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infocliente',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=50),
        ),
        migrations.AddField(
            model_name='infocliente',
            name='tipo_de_figura',
            field=models.CharField(choices=[('Reloj de arena', 'Reloj de arena')], default='Reloj de arena', max_length=50),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='tipo',
            field=models.CharField(choices=[('Personal trainer', 'Personal trainer'), ('Cliente gimnasio', 'Cliente gimnasio'), ('Admin Gym', 'Admin Gym'), ('Cliente normal', 'Cliente normal')], default='Cliente normal', max_length=150),
        ),
    ]
